import Head from 'next/head';
import { useState } from 'react';

// components
import FAQ from '../components/Layout/FAQ';
import Features from '../components/Layout/Features';
import Footer from '../components/Layout/Footer';
import HeaderNetflix from '../components/Layout/HeaderNetflix';
import LoginModal from '../components/Layout/LoginModal';



export default function Home() {

  const [open, setOpen] = useState(false)

  const handleOpenModal = () => setOpen(true)
  const handleCloseModal = () => setOpen(false)


  return (
    <>
      <Head>
        <title>Netflix looks like</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <HeaderNetflix openModal={handleOpenModal} />
      <Features />
      <FAQ />
      <Footer />
      <LoginModal open={open} closeModal={handleCloseModal} />
    </>
  )
}
